# Generated by Django 3.1.3 on 2020-11-22 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20201122_0355'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='type',
            table='Tipo',
        ),
    ]
