# Generated by Django 3.1.3 on 2020-11-22 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20201122_0356'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='type',
            table='tipo',
        ),
    ]
